[package]
name = "haseo"
version = "0.1.3"
edition = "2021"
description = "Haseo is a diff command line made simple."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorize = "0.1.0"
